// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "Pending migration to LoggerMessage.", Scope = "member", Target = "~T:GtMotive.Estimate.Microservice.Infrastructure.Logging.LoggerAdapter`1")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "Pending migration to LoggerMessage.", Scope = "member", Target = "~T:GtMotive.Estimate.Microservice.Infrastructure.Logging.LoggerAdapter`1")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Not null. From dependency injection.", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Infrastructure.MongoDb.MongoService.#ctor(Microsoft.Extensions.Options.IOptions{GtMotive.Estimate.Microservice.Infrastructure.MongoDb.Settings.MongoDbSettings})")]
[assembly: SuppressMessage("Style", "IDE0240:Remove redundant nullable directive", Justification = "Autogenerated code", Scope = "namespace", Target = "~N:GtMotive.Estimate.Microservice.Infrastructure.Data.Migrations")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Autogenerated code", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Infrastructure.Data.Migrations.InitialMigration.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "Autogenerated code", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Infrastructure.Data.Migrations.InitialMigration.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "Autogenerated code", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Infrastructure.Data.Migrations.InitialMigration.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Autogenerated code", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Infrastructure.Data.Migrations.InitialMigration.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
