services:
  gtmotive.estimate.microservice.host:
    image: ${DOCKER_REGISTRY-}gtmotiveestimatemicroservicehost
    build:
      context: .
      dockerfile: GtMotive.Estimate.Microservice.Host/Dockerfile
    depends_on:
      - gtmotive.estimate.microservice.sqlserverdb
      - gtmotive.estimate.microservice.rediscache

  gtmotive.estimate.microservice.sqlserverdb:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: NuevaContra123#
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql

  gtmotive.estimate.microservice.rediscache:
     image: redis:latest
     restart: always
     ports:
       - '6379:6379'
     volumes:
       - redis_volume_data:/data

  gtmotive.estimate.microservice.redisinsight:
    image: redislabs/redisinsight:1.14.0
    restart: always
    ports:
      - "8001:8001"
    volumes:
       - redis_insight_data:/db

volumes:
  dbdata:
  redis_volume_data:
  redis_insight_data:



